
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NUM PA PF VIRG\n    Lista : PA PF\n          | PA NUM Elems PF\n\n    Elems : Elem Resto\n\n    Resto :\n         | VIRG Elem\n\n    Elem : NUM\n         | Lista\n    '
    
_lr_action_items = {'PA':([0,4,11,],[2,2,2,]),'$end':([1,3,9,],[0,-1,-2,]),'PF':([2,3,5,6,7,8,9,10,12,],[3,-1,-6,9,-4,-7,-2,-3,-5,]),'NUM':([2,4,11,],[4,5,5,]),'VIRG':([3,5,7,8,9,],[-1,-6,11,-7,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Lista':([0,4,11,],[1,8,8,]),'Elems':([4,],[6,]),'Elem':([4,11,],[7,12,]),'Resto':([7,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Lista","S'",1,None,None,None),
  ('Lista -> PA PF','Lista',2,'p_gramatica','listas_sin.py',8),
  ('Lista -> PA NUM Elems PF','Lista',4,'p_gramatica','listas_sin.py',9),
  ('Elems -> Elem Resto','Elems',2,'p_gramatica','listas_sin.py',11),
  ('Resto -> <empty>','Resto',0,'p_gramatica','listas_sin.py',13),
  ('Resto -> VIRG Elem','Resto',2,'p_gramatica','listas_sin.py',14),
  ('Elem -> NUM','Elem',1,'p_gramatica','listas_sin.py',16),
  ('Elem -> Lista','Elem',1,'p_gramatica','listas_sin.py',17),
]
