
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "textoZ : DirDir : '(' texto Conteudo ')'Dir : FicheiroConteudo : Conteudo DirConteudo : Ficheiro : '[' texto texto ']'"
    
_lr_action_items = {'(':([0,4,6,8,10,11,12,],[3,-3,-5,3,-2,-4,-6,]),'[':([0,4,6,8,10,11,12,],[5,-3,-5,5,-2,-4,-6,]),'$end':([1,2,4,10,12,],[0,-1,-3,-2,-6,]),'texto':([3,5,7,],[6,7,9,]),')':([4,6,8,10,11,12,],[-3,-5,10,-2,-4,-6,]),']':([9,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Z':([0,],[1,]),'Dir':([0,8,],[2,11,]),'Ficheiro':([0,8,],[4,4,]),'Conteudo':([6,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Z","S'",1,None,None,None),
  ('Z -> Dir','Z',1,'p_Z','dir_sin.py',7),
  ('Dir -> ( texto Conteudo )','Dir',4,'p_Dir_Pasta','dir_sin.py',12),
  ('Dir -> Ficheiro','Dir',1,'p_Dir_Ficheiro','dir_sin.py',17),
  ('Conteudo -> Conteudo Dir','Conteudo',2,'p_Conteudo','dir_sin.py',22),
  ('Conteudo -> <empty>','Conteudo',0,'p_Conteudo_vazio','dir_sin.py',27),
  ('Ficheiro -> [ texto texto ]','Ficheiro',4,'p_Ficheiro','dir_sin.py',32),
]
